// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkw91ixabVvzwwvfNVi4sROzvQve6yQKY',
    appId: '1:505301507872:web:8a27bbb62b69ff1bff8145',
    messagingSenderId: '505301507872',
    projectId: 'investtrack-1c1c4',
    authDomain: 'investtrack-1c1c4.firebaseapp.com',
    storageBucket: 'investtrack-1c1c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5cLA_XWFHSL51sp-9jOS2FOW6k_OYdU',
    appId: '1:505301507872:android:6f3f86dcb05b0737ff8145',
    messagingSenderId: '505301507872',
    projectId: 'investtrack-1c1c4',
    storageBucket: 'investtrack-1c1c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9_zM50iOogksrJ7VlViH60v5a5rBYvfM',
    appId: '1:505301507872:ios:946c5404514b0874ff8145',
    messagingSenderId: '505301507872',
    projectId: 'investtrack-1c1c4',
    storageBucket: 'investtrack-1c1c4.firebasestorage.app',
    iosBundleId: 'com.example.investTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9_zM50iOogksrJ7VlViH60v5a5rBYvfM',
    appId: '1:505301507872:ios:946c5404514b0874ff8145',
    messagingSenderId: '505301507872',
    projectId: 'investtrack-1c1c4',
    storageBucket: 'investtrack-1c1c4.firebasestorage.app',
    iosBundleId: 'com.example.investTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkw91ixabVvzwwvfNVi4sROzvQve6yQKY',
    appId: '1:505301507872:web:b0978089121e64d8ff8145',
    messagingSenderId: '505301507872',
    projectId: 'investtrack-1c1c4',
    authDomain: 'investtrack-1c1c4.firebaseapp.com',
    storageBucket: 'investtrack-1c1c4.firebasestorage.app',
  );
}
